logging:
  level:
    org.hibernate.orm: ERROR
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR

server:
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
  undertow:
    io-threads: 2
    worker-threads: 4
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  metrics:
    binders:
      logback:
        enabled: false
        
        
tch:
  server:
    spring-worker-threads: 10
